TIMEZONE=Asia/Kolkata   # curl --fail https://ipapi.co/timezone
KEYMAP=us               # us | by | ca | cf | cz | de | dk | es | et | fa | fi | fr | gr | hu | il | it | lt | lv | mk | nl | no | pl | ro | ru | sg | ua | uk
FILESYSTEM=btrfs        # btrfs | ext4
DISK=/dev/sda           # disk to install on
DISK_TYPE=ssd           # ssd | non-ssd
DISK_ENCRYPT=encrypt    # encrypt | noencrypt
LUKS_PASSWORD=a         # luks password if encrypting
USERNAME=a              # user name
FULLNAME=a              # user fullname
USER_PASSWORD=a         # user password
ROOT_PASSWORD=a         # root password
HOSTNAME=arch           # hostname of the system
DISTRO_TYPE=arch        # arch | artix
KERNEL=linux            # linux | linux-zen | linux-lts
