#!/usr/bin/env bash

# Find argument count
len="$#"

if [[ "$len" = 1 || "$len" = 0 ]]; then
	echo "Please Give atleast one source and a destination. Allowed Multiple source and one destination only!"
	exit 1
fi

# Destination directory
dst=${@: -1}

if [ -d "$dst" ]; then

	read -p "Are you Sure this will be the destination $(realpath $dst) ? [y/yes] Default yes :" confirm

	if [[ "$confirm" = "y" || "$confirm" = "yes" || "$confirm" = "" ]]; then
		# Declare array
		declare -a my_array
		i=0

		for arg in "${@}"; do
			if [[ "${i}" = $(("${len}" - 1)) ]]; then
				break
			else
				if [ -d "$arg" ]; then
					echo "Folder Detected -> $arg"
					my_array["$i"]="$arg"
				elif [ -f "$arg" ]; then
					echo "File Detected -> $arg"
					my_array["$i"]="$arg"
				else
					echo "Not a file or folder -> $arg"
					echo "Please give input as only files or directories!"
					exit 1
				fi
			fi
			i=$((i + 1))
		done

		# Start copy
		for element in "${my_array[@]}"; do
			src=$(realpath "$element")
			dest=$(realpath "$dst")
			rsync -aPvhW --no-compress --progress --info=progress2 "$src" "$dest"
		done
	else
		exit 1
	fi

else
	echo "Last argument must be a directory which will be the destination where all the files will be copied!"
fi
