#!/bin/bash

replace_line() {
	local file="$3"     # file name
	local line_num="$2" # line number to replace
	local new_line="$1" # new txt
	local tmpFileName="tmp"

	# Check if file exists
	if [[ ! -f "$file" ]]; then
		echo "Error: File '$file' does not exist."
		return 1
	fi

	# Get current line count
	local current_lines=$(sudo wc -l <"$file")

	# Check if line number is within range
	if [[ $line_num -lt 1 || $line_num -gt $current_lines ]]; then
		echo "Error: Line number '$line_num' is out of range."
		return 1
	fi

	# Read file into an array
	local lines=()
	while IFS='' read -r line || [[ -n "$line" ]]; do
		lines+=("$line")
	done <"$file"

	# Replace line at specified index
	lines[${line_num} - 1]="$new_line"

	# Write updated lines back to file
	for element in "${lines[@]}"; do
		touch "$HOME/${tmpFileName}"
		echo "${element}" >>"$HOME/${tmpFileName}"
	done
	sudo mv "$HOME/${tmpFileName}" "$file"
}

if [[ "$1"=="help" && "$2"=="" && "$3"=="" ]]; then
	echo "rlt <txt> <line_number> <file_location>"
fi

if [[ "$1"!="" && "$2"!="" && "$3"!="" ]]; then
	replace_line "$1" "$2" "$3"
fi
