#!/bin/python

import time
import sys
import os
from playsound import playsound

t = 0
target = int(sys.argv[1]) if len(sys.argv) > 1 else None
ALARM_MUSIC = ""
ALARM_SOUND_LOCATION = os.path.expanduser(ALARM_MUSIC)


# Helper
def hours(time):
    return f"{time // 3600}h {minutes(time%3600)}"


def minutes(time):
    return f"{time // 60}m {time%60}s"


def seconds(time):
    return f"{time}s"


# Get time function
def getTime(t):
    # Within minutes
    if t > 60 and t <= 3600 - 1:
        return minutes(t)

    # Within hours
    elif t >= 3600:
        return hours(t)

    else:
        return seconds(t)


while True:
    if t == target:
        print("Time Over!")
        playsound(ALARM_SOUND_LOCATION)
        break
    t += 1
    print(getTime(t), " has passed ...")
    time.sleep(1)
