#!/bin/bash

# Helper
helper() {
	if [ -f "$2" ]; then
		echo "Do Not Do Anything ...!"
	else
		while true; do
			echo "$$" >"$2"
			pgrep "$1" >/dev/null
			if [ $? -ne 0 ]; then
				rm -rf "$2"
				exit 0
			fi
			VOL=$(pamixer --get-volume)
			pactl list sink-inputs | grep -E 'Sink Input #|application.name = "librewolf"' | grep -oP '#\K\d+' | xargs -I{} pactl set-sink-input-volume {} "$VOL%"
		done
	fi
}

# Parse arguments
if [[ "$1" != "" ]]; then
	if [[ "$2" == "" ]]; then
		echo "No Profile given as argument!"
	else
		if [[ "$3" == "librewolf" ]]; then
			librewolf -P "$2" &
			sleep 1
			browser=$(echo "$1" | awk -F":" '{print $1}' | xargs)
			pid=$(echo "$2" | awk -F":" '{print $2}' | xargs)
			helper "$browser" "$pid"

		elif [[ "$3" == "firefox" ]]; then
			firefox -P "$2" &
			sleep 1
			browser=$(echo "$1" | awk -F":" '{print $1}' | xargs)
			pid=$(echo "$2" | awk -F":" '{print $2}' | xargs)
			helper "$browser" "$pid"
		else
			echo "No suppported browser given as argument!"
		fi
	fi
fi
