#!/usr/bin/env bash

soureFolder=""
pattern=""
destinationFolder=""
selectorMenu="no"

printhelp() {
	echo "Arguments Supported:"
	echo "-s Source Folder"
	echo "-p Pattern"
	echo "-d Destination Folder"
	echo ""
	echo -e 'Example 1 : batchmover -s "soureFolder" -p "png" -d "destinationFolder" [Move all PNGs from soureFolder to a destinationFolder]\n'
	echo -e 'Example 2 : batchmover -s "soureFolder" -p "-1" -d "destinationFolder" -m "yes" [Select files with fzf and move them to destinationFolder]\n'
	echo -e 'Example 3 : batchmover -s "soureFolder" -p "png" -d "destinationFolder" -m "yes" [Select png files with fzf and move them to destinationFolder]'
}

while getopts ":s:p:d:m:h" opt; do
	case $opt in
	s)
		soureFolder=$OPTARG
		;;
	p)
		pattern=$OPTARG
		;;
	d)
		destinationFolder=$OPTARG
		;;
	m)
		selectorMenu=$OPTARG
		;;
	h)
		printhelp
		;;
	\?)
		echo "Invalid option: -$OPTARG" >&2
		;;
	esac
done

checkDestinationFolderExists() {
	if [ ! -d "$destinationFolder" ]; then
		mkdir -p "$destinationFolder"
	fi
}

goTODestinationFolder() {
	cd "${destinationFolder}"
}

if [[ "$selectorMenu" = "yes" ]]; then
	if [[ "$pattern" = "-1" && "$soureFolder" != "" && "$destinationFolder" != "" ]]; then
		checkDestinationFolderExists
		filesPresent=$(
			find $(realpath "$soureFolder") -type f | fzf --multi --cycle --prompt "Choose Files to move:" | xargs -ro -I {} cp -r {} "$destinationFolder"
		)
	elif [[ "$pattern" != "" && "$pattern" != "-1" && "$soureFolder" != "" && "$destinationFolder" != "" ]]; then
		checkDestinationFolderExists
		filesPresent=$(
			find $(realpath "$soureFolder") -type f -name "*.$pattern" | fzf --multi --cycle --prompt "Choose Files to move:" | xargs -ro -I {} cp -r {} "$destinationFolder"
		)
	fi
else
	if [[ "$soureFolder" != "" && "$pattern" != "" && "$destinationFolder" ]]; then
		checkDestinationFolderExists
		if [[ "$pattern" = "-1" ]]; then
			find $(realpath "$soureFolder") -type f | xargs -ro -I {} cp -r {} "$destinationFolder"
		else
			find $(realpath "$soureFolder") -type f -name "*.$pattern" | xargs -ro -I {} cp -r {} "$destinationFolder"
		fi
	fi
fi
