#!/usr/bin/env bash

input=$(echo "$(cat -)")
if [[ $(cat -s) =~ $'\n' ]]; then
	echo -e "${input}" | LD_LIBRARY_PATH=/usr/local/bin/bemenu-app/ BEMENU_RENDERERS=/usr/local/bin/bemenu-app/ /usr/local/bin/bemenu-app/_bemenu -i --fb "#282828" --ff "#ebdbb2" --nb "#282828" --nf "#ebdbb2" --tb "#282828" --hb "#282828" --tf "#fb4934" --hf "#fabd2f" --nf "#ebdbb2" --af "#ebdbb2" --ab "#282828" --hp 10 -fn "Fantasque Sans Mono Bold:size=13" "${@}"
else
	echo "${input}" | LD_LIBRARY_PATH=/usr/local/bin/bemenu-app BEMENU_RENDERERS=/usr/local/bin/bemenu-app /usr/local/bin/bemenu-app/_bemenu -i --fb "#282828" --ff "#ebdbb2" --nb "#282828" --nf "#ebdbb2" --tb "#282828" --hb "#282828" --tf "#fb4934" --hf "#fabd2f" --nf "#ebdbb2" --af "#ebdbb2" --ab "#282828" --hp 10 -fn "Fantasque Sans Mono Bold:size=13" "${@}"
fi
